#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/git/functions"

git_local_remote() {
  declare desc="git pre-pull plugin trigger"
  local trigger="git_pre_pull"
  local APP="$1";
  local SOURCE_APP="$(config_get "$APP" SOURCE_APP)"
  local remote_name="source_app_$SOURCE_APP"

  echo "INSIDE!!!!!!!!!!!!!! $APP $SOURCE_APP $remote_name"

  if [[ ! -d "$DOKKU_ROOT/$APP/refs" ]]; then
    true # Skip if there is no git repository in the app.
  elif [[ ! -d "$DOKKU_ROOT/$SOURCE_APP/refs" ]]; then
    true # Skip if there is no git repository in the source app.
  elif git remote show "$remote_name"
    acquire_app_deploy_lock "$APP" "exclusive"
    git fetch "$remote_name"
    release_app_deploy_lock "$APP"
  else
    acquire_app_deploy_lock "$APP" "exclusive"
    git remote add -f "$remote_name" "$DOKKU_ROOT/$SOURCE_APP"
    release_app_deploy_lock "$APP"
  fi
}

git_local_remote "$@"
